resolver: lts-11.0

packages:
- audax
- pholcidae
- spatula
- location:
    git: https://github.com/bitemyapp/esqueleto
    commit: 297f0238419963a386353c75e6fc555a43994ad1
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []
