name:                scraper
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/DebugSteven/coleg-scraper/scraper
license:             BSD3
author:              J Haigh
maintainer:          DebugSteven@gmail.com
copyright:           2017 J Haigh
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude
  - http-conduit
  - conduit
  - bytestring
  - scalpel

library:
  source-dirs:        src
  default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings

executables:
  scraper:
    source-dirs:      app
    main:             Main.hs
    dependencies:     scraper

tests:
  test:
    source-dirs:      test
    main:             Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - scraper
      - QuickCheck
      - hspec
